sudo: false
language: go
branches:
  only:
    - master
    # NOTE: Tagged commits
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
go:
  - 1.12.x
services:
  - docker
os:
  - linux
env:
  - GO111MODULE=on
git:
  depth: 1
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
notifications:
  email: false
before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.16.0
script:
  - go run mage.go -v lint
  - go run mage.go -v test
after_success:
  - go get github.com/mitchellh/gox
  - '[ "${TRAVIS_TAG}" != "" ] && [ "${TRAVIS_GO_VERSION}" = "1.12.x" ] && gox -os="linux darwin" -arch="amd64" -output "dist/{{.Dir}}-${TRAVIS_TAG}_{{.OS}}_{{.Arch}}"'
deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  api_key:
    secure: 3yEfKi7wqdMO07mKLIU1UvNgBraAnydhMHz+UsVzDVkudjd3Z4vIh7IwKJDxr1yCIEe6NgwQsaWpTWbuaHxP3YD/ZBRsorkUr/sECIA39apqSms5A6novx0pvdNxI4WFfcMrcUv9tJoAtq838uwNlH3mbVI/bH9/qQo2pFOiTvSg3My7uc5sm/8bRHB0TxsbadKjGLMp8N41uDCqjr89R9nUK7Xn2jWG5u28X3Ec/CgY3N4GLrUAKZYY88RTFtjxBU/kkk8QpFlGtkdmGfF3qSsrlpc/93xoVWE5vsKEbpwKhNiH1BNVubfIhPHtYhwDWGU7/aHrlHoDVhKRNqBoNtdoiCU3s4e4VE8kHF3AT4QquubSErzwI1JC6ebs46wW/qhPzmcU1lbdnYrsKurKvXxbtHIlLicctUdVt0x6R47GCNtZyIdNkLn4+V2AFUbQEMxU+tsbY6dhyOe1IHorGTSMCtBbKrLJeDOl/cP1iwg3RBHAQyQyCq56H6cV0Dc7wwqLv8fRhcGFFiXoCYbDrQq1D7F66qAaPj7c2dOdvmpu5jG+sMkIfbbonY4I56NSkJ+IvUqUuXlgroWOvlgRe9XETt1vcuiISrJxdi7OJPCbfazuptkxHbfMxNhyUZEC8rb1vcfAerCC3M2ND4IhBhpGKYvFHNVf1K0QZk03qUA=
  file_glob: true
  file: dist/*
  on:
    repo: sumup-oss/terraform-provider-vaulted
    go: 1.12.x
    tags: true
